### ISSUE TITLE
closest code in transformers to noisy channel model 

### ISSUE THREAD

**Issue by jackfeinmann5** [shmsw25/Channel-LM-Prompting#2]
Hi
I am trying to build your codes based on huggingface library examples, could you tell me please which example in HF repo is the closest to your work that you have build on top of it?
thank you

**Comment by shmsw25** [comment]
Thanks for your interest. Actually, I didn't start from the HF example code - I just wrote the code based on the HF documentation. Maybe you can install the HF version mentioned in README and start from this codebase?
