### ISSUE TITLE
yahoo dev sets are missing

### ISSUE THREAD

**Issue by dorost1234** [shmsw25/Channel-LM-Prompting#5]
Hi there
I am using your processed data, thanks for putting them, I realized yahoo dev sets are missing, could you kindly upload them? thanks

**Comment by shmsw25** [comment]
Hi, thanks for your interest. Actually, the dev sets for Yahoo (and more datasets) are missing from the original dataset we used (from Zhang et al. 2015, [link to the original data](http://goo.gl/JyCnZq)). We could have created our own dev data by splitting the training set, but we didn't do it as we do not use the dev data anyways.
